### ISSUE TITLE
[FEATURE] Override changePassword function from ext:felogin

### ISSUE THREAD

**Issue by derhansen** [derhansen/fe_change_pwd#12]
TYPO3 users may still be able to user weak passwords using the forgot password feature of ext:felogin. 

Find a way to hook in to the function in ext:felogin

**Comment by groetzner-net** [comment]
Have you found a solution?

**Comment by derhansen** [comment]
Not so far, did not have time to investigate yet.

**Comment by ja-sk** [comment]
+1 from me for this feature, this would be a very good addition.

**Comment by derhansen** [comment]
For TYPO3 8.7 and 9.5 the only possibility would be to XClass `FrontendLoginController` and to overwrite the method `changePassword`, so additional checks can be implemented. I do not really like such a solution, since changes be adapted to the xclassed version at every change to the main function in the core. Not really something I can support as part of the fe_change_pwd extension.

In TYPO3 V10 the Hook `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['felogin']['password_changed']` has been extended, so it is possible to add further checks to the new password.

**Comment by derhansen** [comment]
This changed in TYPO3 v11 to a PSR-14 event (`PasswordChangeEvent`). Basically I got this working (needed to exclude to "Require current password" validation), but currently there is a open patch in TYPO3 (https://review.typo3.org/c/Packages/TYPO3.CMS/+/69677) which should be added first to get validation working again.

**Comment by derhansen** [comment]
Feature is not needed any more, since ext:felogin can be extended with custom validators using TypoScript - see `settings.passwordValidators`

**Comment by derhansen** [comment]
Internal validator can not be used. Investigate alternative solution.

**Comment by derhansen** [comment]
I will drop this feature and am working on a core implementation for global password policies - see https://forge.typo3.org/issues/97387
