### ISSUE TITLE
ForceRedirect is not working on Typo3 9.5.4

### ISSUE THREAD

**Issue by ShortSnow** [derhansen/fe_change_pwd#13]
Hello,

thanks for this nice script, but it will do no redirect if i set a user to [must_change_password].

A page with the plugin is there, and static template and setup is include. Pid set to the page with the plugin for passwortchange. 

With or without redirects from the login plugin.

Thanks 

Arne Bracht

**Comment by derhansen** [comment]
Can't reproduce the issue.
