### ISSUE TITLE
[FEATURE] check new password against old password

### ISSUE THREAD

**Issue by ja-sk** [derhansen/fe_change_pwd#20]
Great extension, only one thing I found while testing: the "passwordExpiration" feature is neat but without a check against the existing password to make sure it is new it is kind of useless. 

This could probably be done with another check in Classes\Validation\Validator\ChangePasswordValidator.php ... What do you think?

**Comment by derhansen** [comment]
Thanks for your feature request and for your support! It is highly appreciated 👍 

I will add the new check as an optional check for the password validation.

**Comment by derhansen** [comment]
New version available on TER and Packagist
