### ISSUE TITLE
[FEATURE] Add Signal for hooking in after password update

### ISSUE THREAD

**Issue by boettner-it** [derhansen/fe_change_pwd#29]
Hi Torben,

with the 1.5.0 security update the Signal in FrontendUserService is gone. Is there a special reason for that or was it by mistake?

We are sending email notifications to admins on password changes and it would be great to have it back in future versions. I hacked 1.5.0 manually for now.

Best
Robert.

**Comment by derhansen** [comment]
Hi Robert,

which signal are you talking about.  I did never implement any signals to the extension so far. 

Best regards
Torben

**Comment by boettner-it** [comment]
Then this must have happened on our side. I will have to check/ask the colleagues...

Anyway I would like to suggest the Signal. Is the attached patch ok for a quick shot?
[FrontendUserService.patch.zip](https://github.com/derhansen/fe_change_pwd/files/4029909/FrontendUserService.patch.zip)

**Comment by derhansen** [comment]
Thanks, I will add a signal at the suggested place in the code. Naming may defer from your example.

**Comment by boettner-it** [comment]
Great, thanks for accepting the change.

**Comment by derhansen** [comment]
Change has been added to development branch
