### ISSUE TITLE
BUG: Fatal Error plugin Pi1 cannot be determined TYPO3 v9.5.13

### ISSUE THREAD

**Issue by e-webking** [derhansen/fe_change_pwd#37]
"TYPO3\\CMS\\Extbase\\Mvc\\Exception: The default controller for extension \"FeChangePwd\" and plugin \"Pi1\" can not be determined. Please check for TYPO3\\CMS\\Extbase\\Utility\\ExtensionUtility::configurePlugin() in your ext_localconf.php

**Comment by derhansen** [comment]
This is not problem with the extension itself. It can occur in TYPO3, when you changed the Plugin Type of an existing content Element. Please remove the content element completely and create a new one from scratch.

**Comment by derhansen** [comment]
I'm closing this issue, since it is not related to the extension and no further feedback was provided.
