### ISSUE TITLE
[BUG] SQL error if password_expiry_date is empty when creating a fe_user

### ISSUE THREAD

**Issue by sdelcroix** [derhansen/fe_change_pwd#38]
Hi,

there's a sql error occurring when we create a fe_user without setting a expiry date for the password.
We are on MariaDB with a strict mode, and it apparently not allows empty value for a NOT NULL field.

We found a workaround on the forge ( https://forge.typo3.org/issues/82756 ) that adds "int" to the eval in TCA

```
'password_expiry_date' => [
        'exclude' => true,
        'label' => 'LLL:EXT:fe_change_pwd/Resources/Private/Language/locallang_be.xlf:label.password_expiry_date',
        'config' => [
            'type' => 'input',
            'renderType' => 'inputDateTime',
            'eval' => 'datetime,int',
        ]
    ],
```

And we found that "news" extension is using the same workaround for the "datetime" field for instance.

**Comment by derhansen** [comment]
Fix is available in version 2.0.1 on TER and packagist
