### ISSUE TITLE
How to translate messages/title?

### ISSUE THREAD

**Issue by baden32** [derhansen/fe_change_pwd#40]
I have a French website and I would like to get title and error messages in french (I'm still using version 1.5.1 on Typo3 8.7.32).
Under Languages, I've updated the fe_change_pwd package, but I'm still getting every messages/title in English.

Based on other extensions, I tried to add the following TS:

plugin.tx_fechangepwd{

  _LOCAL_LANG.fr {
    currentPassword = Mot de passe actuel
    password = Nouveau mot de passe
    repeatPassword = Répétez le mot de passe
    update = Modifier
    validationErrorHeader = ATTENTION

		passwordsDoNotMatch = Les mots de passe ne correspondent pas
		passwordFieldsEmptyOrNotBothFilledOut = Vous devez saisir votre mot de passe dans les 2 champs
		passwordComplexity.failure.minLength = Le mot de passe doit avoir min. %1s caractères
  }
}

everthing is ok -> validationErrorHeader  (I get the FR title/message), but the 3 following label are not translated.

Is there a bug or am I doing something wrong here?

Thank youin advance for your help.
Joel

**Comment by derhansen** [comment]
Thanks a lot for your report. I have confirmed the issue and it is easy to fix. A new version will be released very soon

**Comment by baden32** [comment]
Hi,
Thanks a lot for your confirmation. As I cannot  upgrade to Typo3 9.x right now, is it possible to integrate the fix in version 1.5.x as well?
Regards
Joel

**Comment by derhansen** [comment]
It is just one line of code that needs to be changed (eb05358). If this works for you, I will also publish a new version of the 1.5 branch

**Comment by baden32** [comment]
Great if a 1.5 patched version could be published.
Thanks a lot in advance.

**Comment by derhansen** [comment]
Fixed in version 2.0.2 and 1.5.2 - Merry christmas

**Comment by baden32** [comment]
Great ! Many thanks and merry Christmas!
