### ISSUE TITLE
Redirect after login does not working

### ISSUE THREAD

**Issue by typo3ua** [derhansen/fe_change_pwd#41]
Hello!

I tried your `ext` but I see that  Redirect after login does not working...

I using TYPO3 9.5.9 with FE Login for login user

I set checkbox in the flexform
`User must change password at next login[must_change_password] = 1`

I added to TS 

UID = 3 it is my the page with form for change password
`plugin.tx_fechangepwd.settings.changePasswordPid = 3`

**Comment by derhansen** [comment]
The default setting of the extension is to redirect the fe_user to the configured `changePasswordPid` as soon as the user accesses an **access protected page** (see this [setting](https://github.com/derhansen/fe_change_pwd/blob/master/Configuration/TypoScript/setup.txt#L55)).

So if your `ext:felogin` redirect after login does not redirect the user to a access protected page, then the Redirect to configured `changePasswordPid ` will not occur. 

Please check possible settings in `plugin.tx_fechangepwd.settings.redirect` and adjust those to your needs.

**Comment by typo3ua** [comment]
Thank you for your reply... Yes, I tried and tried different setting but I can not to force it to work...

It is all very difficult

I went another way ... I have used ext:form and TypoScript condition ... now I have what I need...

Thank for your support
