### ISSUE TITLE
[BUG] Composer / PSR-4 compatibility

### ISSUE THREAD

**Issue by dennismetz** [derhansen/fe_change_pwd#42]
Wrong namespace in Exception\InvalidUserException.php and MissingPasswordHashServiceException.php

namespace Derhansen\FeChangePwd\Service; -> namespace Derhansen\FeChangePwd\Exception;

Class Derhansen\FeChangePwd\Service\InvalidUserException located in ..../typo3conf/ext/fe_change_pwd/Classes\Exception\InvalidUserException.php does not comply with psr-4 autoloading standard. Skipping.

Class Derhansen\FeChangePwd\Service\MissingPasswordHashServiceException located in .../typo3conf/ext/fe_change_pwd/Classes\Exception\MissingPasswordHashServiceException.php does not comply with p
sr-4 autoloading standard. Skipping.

**Comment by derhansen** [comment]
Thanks a lot. I merged both PRs
