### ISSUE TITLE
Issue with loacalization of change password extension

### ISSUE THREAD

**Issue by aiturria-spain** [derhansen/fe_change_pwd#60]
Good afternoon

I tried to translate the extension to use it in different languages e.g. German, Italian, Polish, Hungarian etc.

I have a TypoScript file containing all translations for the required languages. Unfortunately it works only fine for German and English.

Just a small fragment from my TypoScript file:

plugin.tx_fechangepwd._LOCAL_LANG.de {

    changePasswordReason.header = Passwort ändern

    password = Neues Passwort

    repeatPassword = Passwort wiederholen

    update = Speichern

    passwordFieldsEmptyOrNotBothFilledOut = Sie müssen beide Felder ausfüllen

    passwordsDoNotMatch = Die Passwörter stimmen nicht überein

    validationErrorHeader = Überprüfen Sie bitte folgende Eingabefehler:

    changePasswordReason.forcedChange = Sie müssen Ihr Passwort ändern

}

The configuration for the other languages (it,es,da,pl etc.) is the same to the german language. What I'm doing wrong here?

Thanks a lot for your help.

Kind regards

Alberto

**Comment by derhansen** [comment]
The described problem is not related to the extension but seems to be a local TYPO3 configuration issue on your website.

Please make sure, you setup TYPO3 language handling as described in the TYPO3 documentation and that overwritten language codes (in TypoScript) actually match configured system locales.

This example works fine for the language `danish` (language code: `da`):

```
plugin.tx_fechangepwd._LOCAL_LANG.da {
  validationErrorHeader = Test
  passwordFieldsEmptyOrNotBothFilledOut = Test
}
```
