### ISSUE TITLE
[FEATURE] Require email authentication in order to change current password

### ISSUE THREAD

**Issue by baschny** [derhansen/fe_change_pwd#69]
As an additional security layer, to be sure that the person which is changing the password still has access to its own email address, it would be cool to be able to configure an (optional) email confirmation token. 

The use case is: your frontend users are required to be employees of certain companies, meaning that they are required to have access to their email accounts. Once the employee leaves the company and has no longer access to their former email-address, next time they are forced to change the password on the site, they but won't be able to, since it requires to confirm that via an email token.

So a new plugin would be required which triggers the "desire to change the password", sending an email with a "token" to the user (i.e. the "username" or the "email" field) and only if this email link is activated, he is presented with the "change password" plugin - as this extension already provides.

**Comment by derhansen** [comment]
@baschny I have a question to the use case: How is it defined, that the user must change the password? Is this a manual process (e.g. backend user edits frontend user record and checks "User must change password at next login")? If this is a manual process as described, I think it is a better workflow to disable the frontend user record or to manually reset the password in backend context. 

I would like to avoid to create an additional plugin, but can think of extending the extension as following:

Add another configuration option (e.g. `requireEmailVerificationCode`). If this option is configured, the plugin will generate a verification code and save it (as hash) to the frontend users record. Additionally the validity time of the verification code is saved to the frontend user record. After the verification code is generated saved, an email is sent to the user. The plugin will initially display a flash message, that a verification code has been sent. 

The change password plugin will then require the user to enter the new password, the current (if configured) and the verification code received by email. The plugin then only allow the password change, if the verification code is valid and not expired.

**Comment by baschny** [comment]
The usecase plans to use the "password expiration feature" so that any new user is setup so that the password expires in 6 months. So every 6 months the user has to change its password, and at this time he has also to validate that he still has access to his email address.

I like your idea a lot, coupling the same plugin with an additional "secret" that he has to input (i.e. a 6 digit number) sound great.

I did not understood when exactly you want to generate the verification code and thus also send the email. You mean to do that whenever the user is presented with the change-password-plugin and has not yet a stored code along with his fe-user? There might then also be the need to "please resend the code" in case the user did not receive it at first.

**Comment by derhansen** [comment]
After re-thinking and reading your comment, I think the best option to send the verification code is manually through a link on the page where the user has to enter change the password. So we could display a link "Send verification code" below the input field for the verification code, which when clicked, generates the code and sends the email.

**Comment by baschny** [comment]
That sounds good, as its always better to only send mails to people if they actively agree in doing that - so that they also know when to expect the mail (to check the spam folder ...).

**Comment by derhansen** [comment]
Implemented in version 3.1.0 and 4.1.0
