### ISSUE TITLE
[FEATURE] Allow to configure sending e-mail address for passwort change code

### ISSUE THREAD

**Issue by baschny** [derhansen/fe_change_pwd#76]
The feature "change password code per email" (`requireChangePasswordCode`) is nice, but it lacks the possibility to configure the sending email address (and sender "realname"). For example like also `felogin` does (settings `email_from` and `email_fromName`).

That would be useful!

**Comment by derhansen** [comment]
Resolved in versions 3.2.0 and 4.2.0
